name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Posts
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/posts-service ./services/posts
        docker push ${{ secrets.DOCKER_USERNAME }}/posts-service

    - name: Build & Push Comments
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/comments-service ./services/comments
        docker push ${{ secrets.DOCKER_USERNAME }}/comments-service

    - name: Build & Push Query
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/query-service ./services/query
        docker push ${{ secrets.DOCKER_USERNAME }}/query-service

    - name: Build & Push Event Bus
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/event-bus-service ./services/event-bus
        docker push ${{ secrets.DOCKER_USERNAME }}/event-bus-service

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/devsecops-project/k8s
          kubectl apply -f .
          kubectl rollout restart deployment posts
          kubectl rollout restart deployment comments
          kubectl rollout restart deployment query
          kubectl rollout restart deployment event-bus